apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: packersmovers
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 4
  replicas: 20
  minReadySeconds: 10
  selector:
    matchLabels:
      app: packersmovers
  template:
    metadata:
      labels:
        app: packersmovers
    spec:
      containers:
      - name: customer
        image: 533266968694.dkr.ecr.ap-south-1.amazonaws.com/customer:2
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
